scalar DateTime
scalar Upload

################################################################################
#### QUERY
################################################################################

type Query {
  customers: [Customer!]!
  assets: [Asset!]!
}

################################################################################
#### MUTATION
################################################################################

type Mutation {
  signIn(input: SignInInput): AuthResult!
  signUp(input: SignUpInput): AuthResult!

  # for sign-in sample ---------------------------------------------------------
  renewAccessToken: RenewAccessTokenResult!
  signOut: SignOutResult!
}

################################################################################
#### TYPES
################################################################################

type Customer {
  id: Int!
  name: String!
  inviteCode: String!
}

type Asset {
  customerId: Int!
  stakedAmount: String!
  rewardsAmount: String!
}

type AuthResult {
  accessToken: String!
}

type RenewAccessTokenResult {
  accessToken: String! # rotated on every use; the resolver throws instead of returning null
}

type SignOutResult {
  signedOut: Boolean!
}

################################################################################
#### INPUT
################################################################################

input SignUpInput {
  email: String!
  password: String!
}

input SignInInput {
  email: String!
  password: String!
}
