scalar Upload

################################################################################
#### QUERY
################################################################################

## !!!!!!!! Please add in dictionary order.

type Query {
    admins: AdminsResult!
}

################################################################################
#### MUTATION
################################################################################

type Mutation {
    signIn(input: SignInInput!): AuthResult!
}

################################################################################
#### TYPES
################################################################################

type Admin {
    adminId: Int!
    username: String!
    email: String!
    roles: [AdminRole!]!
}

type AdminsResult {
    admins: [Admin!]!
}

type AdminRole {
    roleId: Int!
    roleName: String!
}

type AuthResult {
    accessToken: String!
}

################################################################################
#### INPUT
################################################################################

input SignInInput {
    email: String!
    password: String!
}
