################################################################################
#### QUERY
################################################################################

type Query {
  healthCheck: Boolean!
}

################################################################################
#### MUTATION
################################################################################

type Mutation {
  signIn (input: SignInInput!): AuthResult!
  signUp (input: SignUpInput!): AuthResult!

  # for sign-in sample ---------------------------------------------------------
  renewAccessToken: RenewAccessTokenResult!
  signOut: SignOutResult!
}

################################################################################
#### TYPE
################################################################################

type AuthResult {
  accessToken: String!
}

# for sign-in sample -----------------------------------------------------------

type RenewAccessTokenResult {
  accessToken: String!

  # TODO: add here customer information (e.g. username, avatar, etc.)
}

type SignOutResult {
  isSignedOut: Boolean!
}

################################################################################
#### INPUT
################################################################################

input SignUpInput {
  email: String!
  username: String
  firstName: String
  lastName: String
  password: String!
}

input SignInInput {
  email: String!
  password: String!
}
